categories: [Metagenomics]
description: Galaxy wrapper for KrakenTools
homepage_url: https://github.com/jenniferlu717/KrakenTools
long_description: A suite of scripts to be used for post-analysis of Kraken/KrakenUniq/Kraken2/Bracken
  results.
name: kraken_tools
owner: youyuh48
remote_repository_url: https://github.com/youyuh48/galaxy-tools/tree/master/tools/KrakenTools
