categories: [Sequence Analysis]
description: Galaxy wrapper for sniffles
homepage_url: https://github.com/fritzsedlazeck/Sniffles
long_description: Structural variation caller using third generation sequencing
name: sniffles
owner: youyuh48
remote_repository_url: https://github.com/youyuh48/galaxy-tools/tree/master/tools/sniffles
